; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B9BA3238-6400-45E0-95FF-7EAFE20EF301}
AppName=DelPapa Gaming Software
AppVersion=3.5
;AppVerName=DelPapa Gaming Software 3.5
AppPublisher=DelPapa Dist.                                   
AppPublisherURL=https://delpapadistributing.com/
AppSupportURL=https://delpapadistributing.com/
AppUpdatesURL=https://delpapadistributing.com/
DefaultDirName=C:\DelPapa Gaming Software
DisableDirPage=yes
DefaultGroupName=DelPapa Gaming Software
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\afroe\Desktop\Lookup\DelPapa_logo_circle.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\afroe\Desktop\Lookup\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

